# Generated by Django 5.2.4 on 2026-02-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='matched_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
