# Generated by Django 5.2.4 on 2026-02-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_matched_keywords_resume_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job_role',
            field=models.CharField(choices=[('python_dev', 'Python Developer'), ('frontend_dev', 'Frontend Developer'), ('data_analyst', 'Data Analyst')], default='python_dev', max_length=50),
        ),
    ]
